### ISSUE TITLE
Revisar tema de canal de YouTube

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#111]
1. Transmision en vivo para 87 personas
2. Hay que administrar la cuenta, para organizar y compartir videos
3. Se deben alcanzar los 1000 subscriptores para obtener las opciones completas de la funcion detransmitir en vivo

Hay que coordinar con mercadeo para que gestionen la cuenta.

Correo: parquedelrecuerdo@pdr.com.pa

**Comment by jdpalermo** [comment]
@pdrlcabeza que necesitas que revise? o me estas informando que estamos listos? 

Por otro lado conseguir 1,000 subscritores esta duro, si esto mas que todo es para hacer transmisiones que la gente va a ver y luego ya se sale... quizas si hicieramos misas los domingos. ... tendriamos que dar ese enfoque

**Comment by pdrlcabeza** [comment]
@jdpalermo  aqui seria practicamente entregar ya la admnistracion del canal de youtube y mitrar si requieren algo mas.

**Comment by pdrlcabeza** [comment]
@jdpalermo  Les escribi a todos los involucrados, cierro esta tarjeta y quedo a la espera de que Liany consteste a ver si necesita algun otro apoyo con eso.
