### ISSUE TITLE
Reporte de Colon Diario de Ventas y Cobros COLON

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#141]
## Job: esta enviando los resultados mezclados con datos de Panama

**Comment by pdrlcabeza** [comment]
@jdpalermo  listo, hacia falta un ajuste y se reinicio el server debe llegar a partir de mañana sin ningun detalle
![image.png](https://images.zenhubusercontent.com/62950aecf415b86a27660458/60a1cc23-4925-4e6a-ac91-c574a8913a49)

**Comment by jdpalermo** [comment]
@pdrlcabeza el titulo del reporte dice Panama Colon.... no deberia ser solo Colon?
