### ISSUE TITLE
Recuperacion de dominio RE GP

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#150]
Monica 

Esto te lo mande hace muchísimo y lo volví a mandar en varias ocasiones posteriores.   Vamos a ver qué se puede hacer.  Seguro se rescata pero probablemente se ha perdido información y quizás el valor de promoción ya pasó. 

Quizás es una oportunidad para que ellos pase a un hosting de ellos y contraten directamente todo

Luis. Puede hablar con la gente e de google sobre este tema. 
Antes de contratar veamos si podemos abrirle su propia cuenta de hosting y pasarles el dominio. 

Saludos,

José D. Palermo
Gerente General
Parque del Recuerdo

Begin forwarded message:

From: Mónica Palermo <monica@grupopalermo.com>
Date: August 26, 2022 at 10:55:17 AM EST
To: Mino Palermo <jose@grupopalermo.com>
Subject: Re: Hai ancora 21 days di tempo per configurare i dati di fatturazione di Google Workspace Business Starter per panama-re.com

﻿Me dicen que sí lo van a querer, que si lo podemos renovar y qué les pase la cuenta. 

El 07/25/2022, a las 8:52 a. m., Jose Palermo M. <jose@grupopalermo.com> escribió:

Tienes que decirles a los panama-re que ahora toca pagar por las cuentas y qué hay que hacer una cuenta con google.  
Los podemos ayudar si quieren pero necesitan definir que correos son para comprar el paquete de cuentas con el proveedor.  Eso se paga anualmente.  

Saludos,

José D. Palermo
Gerente General
Parque del Recuerdo

Begin forwarded message:

From: The Google Workspace Team <workspace-noreply@google.com>
Date: July 25, 2022 at 8:10:35 AM EST
To: jose@grupopalermo.com
Subject: Hai ancora 21 days di tempo per configurare i dati di fatturazione di Google Workspace Business Starter per panama-re.com
Reply-To: The Google Workspace Team <workspace-noreply@google.com>

﻿
Google Workspace	
Non perderti Google Workspace Business Starter
Ci risulta che tu non abbia configurato i dati di pagamento relativi all'abbonamento a Google Workspace Business Starter per panama-re.com. Hai tempo fino al giorno 15 agosto 2022 per configurare i dati di fatturazione. Al termine di questo periodo, il tuo abbonamento sarà sospeso.

Per impedire la sospensione di tutti i servizi per tutti gli utenti, accedi alla Console di amministrazione Google. Fai clic su Fatturazione e segui i passaggi per configurare la fatturazione e i pagamenti per Google Workspace.

Consulta le istruzioni complete per correggere i problemi di pagamento e fatturazione oppure contatta il nostro team di assistenza per ricevere ulteriore supporto.

Accedi
Cordiali saluti,

Il team di Google Workspace
Google Workspace
© 2022 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043

Ti abbiamo inviato questa email di servizio obbligatoria per informarti di importanti cambiamenti che interessano il tuo account o prodotto Google Workspace.

**Comment by pdrlcabeza** [comment]
@jdpalermo  Se llamo por segunda vez a Google, estan dando celeridad al caso. Aun esperando respuesta.

**Comment by pdrlcabeza** [comment]
@jdpalermo 

Greta Gonzalez
14:06 (hace 12 minutos)
para mí, Tania, Luis

Buenas tardes don Luis,

Ya le tengo información, el dominio panama-re.com aparece ante Google con 13 usuarios suspendidos (adjunto imagen), el Super Administrador es  antonio@panama-re.com Antonio D., el cual no ingresa desde el 17 de Mayo 2018.

Si perdieron las contraseñas para ingresar puede realizar los siguientes pasos  
1. inicie sesión en admin.google.com
2. Ingrese el correo electrónico del superadministrador y seleccione ¿Olvidó la contraseña?
3. cuando solicite verificación por correo electrónico y teléfono, seleccione probar de otra manera
4. Al omitir los dos pasos, el sistema le hará las siguientes preguntas de verificación
4.1 - nombre y apellido
4.2 - nombre de la empresa (casi siempre el mismo que el nombre de dominio)
4.3 - última vez que accedió a la cuenta (mes/año)
5. Una vez hecho esto, el sistema libera un código que debe ingresarse en el panel de host del cliente 
6.después de 30 segundos el sistema solicitará una nueva contraseña y se recuperará el panel

Por favor indíqueme cuantas cuentas desean comprar, se mantendrán en Google Workspace Business Starter, desea la propuesta para 1 o 3 años y a cuál nombre de empresa le cotizo?
Saludos cordiales,
![image.png](https://images.zenhubusercontent.com/62950aecf415b86a27660458/8142c7a1-7867-43a4-a812-fff49371ec45)

**Comment by pdrlcabeza** [comment]
@jdpalermo me dicen que no perderan los correos por ahora.

**Comment by jdpalermo** [comment]
@pdrlcabeza has visto algo de sto con mi hermana?

**Comment by pdrlcabeza** [comment]
@jdpalermo si,  hablamos  dos veces, la ultima vez dijo que esperaba respuesta de la persona acerca de las cuentas.

**Comment by pdrlcabeza** [comment]
@jdpalermo 
![image.png](https://images.zenhubusercontent.com/62950aecf415b86a27660458/625f4ae4-16e8-4ffc-8b42-eb4bc5710d7a)

**Comment by pdrlcabeza** [comment]
@jdpalermo  no van a requerir las cuentas de correo, se procede a ccerrar la solicitud.
