### ISSUE TITLE
Finalizacion KANBAN ERP + Revision + Puesta en Marcha

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#159]

**Comment by pdrlcabeza** [comment]
- [x] 1. Error de visualizacion al no dar el permiso de administracion
- [x]  2. Actualizacion Epic en tiempo real
- [x]  3. Revisar las notificaciones de comentarios
- [x]  4. No incluir a los que no son parte del repositorio en:
- [x]  A. Asignacion de tarjeta
- [x]  B. Comenatarios
- [x]  5. Margen de contenedor de tarjeta
- [x]  6. Filtro de EpICS
- [ ]  7. Ponderacion de tarjetas al inicio de columna
- [x]  8. Comment no trae el avatar correcto
- [x]  9. Inicio Board Inicial Traer todas las tarjetas de los repos asignados al usuario

**Comment by jdpalermo** [comment]
@pdrlcabeza ya esta todo?

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/b9836858-b2ce-4486-9787-b6cf744d4980/download](https://app.zenhub.com/files/498768118/b9836858-b2ce-4486-9787-b6cf744d4980/download)

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/87ce160a-7aa0-4e4b-910e-8cce5a7ed764/download](https://app.zenhub.com/files/498768118/87ce160a-7aa0-4e4b-910e-8cce5a7ed764/download)

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/5a66ac80-fe7c-4f0b-ac17-ef9c15bbf0eb/download](https://app.zenhub.com/files/498768118/5a66ac80-fe7c-4f0b-ac17-ef9c15bbf0eb/download)

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/3c4bc961-97c0-405c-adf1-9aeda05175c1/download](https://app.zenhub.com/files/498768118/3c4bc961-97c0-405c-adf1-9aeda05175c1/download)

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/895a4842-69a3-49db-8d39-5ca7c026478f/download](https://app.zenhub.com/files/498768118/895a4842-69a3-49db-8d39-5ca7c026478f/download)
