### ISSUE TITLE
Solicitud de Mensaje de Voz Hato Viejo

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#168]
El ingeniero solicita que cuando no este Liset en el puesto,  sus llamadas puedan caer en un buzon de voz, nosotros no tenemos buzon de voz en la central, lo que se podria hacer es dirigir las llamadas a celular y alli en clinete deje el mensaje de voz. No lo veo como una buena solucion pero es lo que se podria hacer. 

Liset prefiere no reenviar las llamadas a su telefono personal, por lo cual una linea de 3.50 con numero dentro del pool podria ser una alternativa. 

Ella recibe llamadas de :
2801016 Directo
2801040 Consulado
2801090 Hato Viejo
2801091 Centro Logistico

Que opinas?

**Comment by jdpalermo** [comment]
@pdrlcabeza claro, su numero personal es su numero personal.   Pero tampoco quiero saltar a hacer cosas asi, hay ver que nos conviene.

**Comment by pdrlcabeza** [comment]
@jdpalermo  te parece seguir asi como estamos, y ver que pasa mas adelante?, yo creo que pudo ser un tema de que posiblemente estaba Liset en el baño y el vio el telefono sonando.
