### ISSUE TITLE
Ingreso a Inventario - Ajuste de inventario

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#24]
revisar el ajuste de inventario e ingreso de inventario, las cantidades se van a negativo en la segunda carga, el ajuste de inventario no esta funcionando.

Si algun item se va a justar deberia rremplazar a la cantidad existente y guardar el registro de la accion.

**Comment by freddan58** [comment]
Ajuste Publicado en el server para revisión
