### ISSUE TITLE
Actualización del Framework 4.5 (fuera de soporte) al 4.8

### ISSUE THREAD

**Issue by freddan58** [jdpalermo/Software-Development#29]

**Comment by freddan58** [comment]
Se debe realizar la actualización al Framework 4.8 de los proyectos, por obsolescencia del framework 4.5.y problemas de compatibilidad en algunas librerias nuevas.

https://dotnet.microsoft.com/en-us/download/dotnet-framework/net45

**Comment by pdrlcabeza** [comment]
@freddan58 dejame saber
