### ISSUE TITLE
Mejoras - Bugs - Ajustes de Invoice to pay

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#32]
#    Job to be done
##  Listado de mejoras / definirlas para pasar a corrección 

- [x] Pantalla de details de orden de compra, homolgar su formato
- [x] Update de invoices
- [x] Update de payments debe decir cual fue le update que se realizo
- [x] Mostrar el nombre del pago como titulo
- [x] Pop-up de informacion al pasar el mouse por encima del pago

**Comment by rjavier001** [comment]
Mostrar el nombre del pago como titulo  (**DONE**)

Tareas realizadas:
1. SP_PoPaymentsListBySupplier (Actualizado)
2. SP_PoPaymentsList (Actualizado)
3. Modelo (Actualizado)

**Comment by rjavier001** [comment]
Update de payments debe decir cual fue le update que se realizo **(DONE)**

Tareas realizadas:

1. Controlador POPAYMENTS-WEB (Actualizado)
2. Controlador POPAYMENTS-API (Actualizado)

**Comment by rjavier001** [comment]
Pop-up de información al pasar el mouse por encima del pago (**DONE**)

Tareas realizadas:

1. View _KabanDetail (Actualizado)
2. View Board (Actualizado)
3. Script PoPaymentsKabanDetail (Agregado)
