### ISSUE TITLE
JD - LC ERP Hato Viejo Rev.1 update 5

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#60]
Posiblemente RHV + TC  + Fdeveloper 
Definir proximos pasos para cerrar.

- [ ] Creacion de Propiedad :
Passoword de la Nit debe estar hint en su creacion.
Los datos que son accesorios deben quedar opcionales para editar luego.
Pantalla de creacion sera rediseñada, debe ser una sola pantalla y solo debe pedir el nombre, todos los demas datos deben ser editables. Tal vez mirar como lo hacen los bienes raices.
Hay datos que por estructura deben quedar rellenos por debajo.

- [ ] Lector de documentos en linea sin tener que bajarlos.

- [ ] Compañia seria Grupo Economico

- [ ] En la edicion seria esto:
Tipo:        Arrendamiento: Finca y Propiedad Horizontal
Su-Tipo   

- [ ] Detalle de Propiedad Folio real , dejar un par de campos por si despues se requieren.

**Comment by jdpalermo** [comment]
![Properties - Creacion de una nueva 1 .png](https://images.zenhubusercontent.com/5e0106a2563ec6f478522745/8f9a613b-9c95-4783-a000-58802d3e6fe2)
![Properties - Creacion nueva 2.png](https://images.zenhubusercontent.com/5e0106a2563ec6f478522745/c860f554-d054-4081-af12-882b87d0a287)
![Properties - Creacion nueva 3.png](https://images.zenhubusercontent.com/5e0106a2563ec6f478522745/1903af08-618c-40be-9f77-3b6d31d8f033)
![Captura de Pantalla 2022-06-29 a la(s) 12.40.24 p. m..png](https://images.zenhubusercontent.com/5e0106a2563ec6f478522745/c2d72ac2-a217-49a6-9e4d-1fc0e2f58419)
[https://app.zenhub.com/files/498768118/104aa4fb-b29a-41f6-be5e-eca7dd9c1237/download](https://app.zenhub.com/files/498768118/104aa4fb-b29a-41f6-be5e-eca7dd9c1237/download)

**Comment by pdrlcabeza** [comment]
@jdpalermo  esta seman se compila en un requerimiento.
