### ISSUE TITLE
Cotizacion de trabajo Configurar Banco General directo con PayDay

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#82]
### Descripcion

- Interfaz de pago a los Acreedores por ACH con Banco General.
- Interfaz de pago a los Empleados por ACH con Banco General.

**Comment by pdrlcabeza** [comment]
[https://app.zenhub.com/files/498768118/a951aae7-5f07-405a-a16a-f338a57fdf0a/download](https://app.zenhub.com/files/498768118/a951aae7-5f07-405a-a16a-f338a57fdf0a/download)

**Comment by pdrlcabeza** [comment]
@jdpalermo Este trabajo hay que realizarlo para el cambio de Global a Banco General

**Comment by jdpalermo** [comment]
@pdrlcabeza ya esto se estaba haciendo por global??? lo que se tenia en global queda verdad? porque si en algun momento queremos usarlo debemos poder.

**Comment by pdrlcabeza** [comment]
@jdpalermo  la configuracion de global quedara alli, esta nueva seria del banco general.

**Comment by jdpalermo** [comment]
@pdrlcabeza procedamos
